-- Per-skill "market snapshot": pay ranges, demand, AI impact, and current
-- trends. Generated by AI and cached (one row per skill); publicly readable so
-- the landing page can show it before sign-in. Service-role writes only.
create table public.skill_market (
  skill_id        uuid primary key references public.skills (id) on delete cascade,
  pay_beginner    text not null,   -- e.g. "₦80k–₦200k/mo or $5–$15/hr freelance"
  pay_experienced text not null,
  demand_outlook  text not null,   -- 1-2 sentences on job/gig demand
  ai_impact       text not null,   -- how AI changes this skill + how to stay relevant
  trends          jsonb not null default '[]'::jsonb, -- array of short strings
  model_used      text,
  generated_at    timestamptz not null default now()
);

alter table public.skill_market enable row level security;

-- World-readable (landing page shows it pre-auth); writes go through the
-- service role, which bypasses RLS.
create policy "skill_market: public read"
  on public.skill_market for select using (true);
